debug: true
demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  qos:
    port: 22223
  registry:
#    配置是否使用注册中心
#    address: zookeeper://127.0.0.1:2181
    address: N/A
    id: my-registry1
  consumer:
    filter: traceFilter
endpoints:
  dubbo:
    enabled: true
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    dubbo:
      status:
        defaults: memory
  server:
    port: 8081
server:
  port: 8080
spring:
  application:
    name: dubbo-consumer-demo
